### ISSUE TITLE
Move to K8s CRDs

### ISSUE THREAD

**Issue by galexrt** [galexrt/elasticsearch-operator#4]
**TODO**:
- [ ] Rebase on coreos/prometheus-operator source
- [ ] Fix bugs from rebase
- [ ] Modify RBAC to suit elasticsearch-operator
